name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_SECRET }}        
        run: |
          chmod +x ./gradlew
          echo $NMEDIA_SECRET > app/google-services.json     
        
          ./gradlew build --info

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
